[project]
name = "clientmanager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai-tools[mcp]>=0.60.0",
    "crewai[tools]>=0.157.0",
    "python-dotenv>=1.1.1",
]
